name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Exec ShellCheck
      run:
        shellcheck -f diff *.sh

  test:
    name: Archlinux-shellspec
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: |
        sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist
        sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
        pacman -Sy --noconfirm
        pacman -S git --noconfirm
        curl -fsSL https://git.io/shellspec | sh -s -- --yes
        pacman -S firefox chromium diffutils --noconfirm
        pacman -S dash zsh --noconfirm
    - name: Run shellspec for bash
      run:
        /github/home/.local/bin/shellspec -s /bin/sh
    - name: Run shellspec for dash
      run:
        /github/home/.local/bin/shellspec -s /bin/dash
    - name: Run shellspec for zsh
      run:
        /github/home/.local/bin/shellspec -s /bin/zsh
