name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Exec ShellCheck
      run:
        shellcheck -f diff *.sh
