name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Exec ShellCheck
      run:
        shellcheck -f diff *.sh

  test:
    name: Archlinux-shellspec
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repo under workspace
      uses: actions/checkout@v3

    - name: Create image tag
      id: imagetag
      run: |
        TAG="arch-shellspec-$(date +%Y%U)"
        PATH="/tmp/docker/${TAG}.tar"
        echo "::set-output name=TAG::${TAG}"
        echo "::set-output name=PATH::${PATH}"

    - name: Enable cache
      id: cache
      uses: actions/cache@v2
      with:
        path: /tmp/docker
        key: ${{ steps.imagetag.outputs.TAG }}

    - name: Load Docker image if exists
      if: steps.cache.outputs.cache-hit == 'true'
      run: docker load --input ${{ steps.imagetag.outputs.PATH }}

    - name: Build Docker image and save
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p /tmp/docker
        docker build -f '${{ github.workspace }}/.github/workflows/Dockerfile' -t ${{ steps.imagetag.outputs.TAG }} .
        docker save --output ${{ steps.imagetag.outputs.PATH }} ${{ steps.imagetag.outputs.TAG }}

    - name: Start docker container
      run:
        docker run -dit --init -v ${{ github.workspace }}:/mnt --name test-runner ${{ steps.imagetag.outputs.TAG }} /bin/dash
    - name: Run shellspec for bash
      run:
        docker exec test-runner /bin/dash -c "cd /mnt/; /root/.local/bin/shellspec -s /bin/bash"
    - name: Run shellspec for dash
      run:
        docker exec test-runner /bin/dash -c "cd /mnt/; /root/.local/bin/shellspec -s /bin/dash"
    - name: Run shellspec for zsh
      run:
        docker exec test-runner /bin/dash -c "cd /mnt/; /root/.local/bin/shellspec -s /bin/zsh"
